blank_issues_enabled: false
contact_links:
  - name: Autocomplete Style Suggestions - Issues
    url: https://github.com/orgs/community/discussions/categories/copilot
    about: For general Copilot issues beyond chat, please use the Copilot GitHub Discussions.
  - name: AI Model - Issues
    url: https://aka.ms/vscode-copilot-survey
    about: The issue tracker is not for AI model issues - please use the VS Code Copilot survey.
