name: Run assignableUsers.sh

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Run script
      run: |
        query='query RepositoryAssignableUsers($endCursor:String$name:String!$owner:String!){repository(owner: $owner, name: $name){assignableUsers(first: 100, after: $endCursor){nodes{id,login,name},pageInfo{hasNextPage,endCursor}}}}'
        variables='{"endCursor":null,"name":"vscode-copilot-release","owner":"microsoft"}'
        curl -X POST \
          -H "Authorization: bearer $GH_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"query\":\"$query\",\"variables\":$variables}" \
          https://api.github.com/graphql
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
